class Event:
    """    
    EVENT_TYPES: 
        0 - Txn is Generated by a Node\n
        1 - Txn Sent from a Node to its Peers\n
        2 - Mined Block by a Node Sent to its Peers\n
        3 - Mined Block by a Node Ready to Process by Self\n
    """
    def __init__(self, time, type=0, transaction=None, block=None, senderPeer=None, receiverPeer=None):
        self.time = time
        self.type = type
        self.transaction = transaction
        self.block = block
        self.senderPeer = senderPeer
        self.receiverPeer = receiverPeer
    